


apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: secret-inject 
  namespace: default
spec:
  vault:
    name: oz638q # name of azure key vault
    object:
      name: secret01 # name of the azure key vault object
      type: secret # azure key vault object type


