
# kubectl expose deployment app --type=LoadBalancer --name=app --port=3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      securityContext:
        # runAsUser: 1000
        # runAsGroup: 1000
        # runAsNonRoot: true
      containers:
      - name: app
        image: app
        imagePullPolicy: Never
        env:
        - name: TYPE
          value: "app"
        # - name: TEST_SECRET
        #   value: "secret-inject@azurekeyvault" # ref to akvs
        volumeMounts:
        - name: app-secret
          mountPath: "/etc/secrets"
          readOnly: true
        securityContext:
          # readOnlyRootFilesystem: true
          # privileged: false
          # allowPrivilegeEscalation: false
      volumes:
      - name: app-secret
        secret:
          secretName: app-secret
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: default
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
---
# add a simple kubernetes secret 
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: default
type: Opaque
data:
  username: dG9wc2VjcmV0dXNlcm5hbWU=  # Base64 encoded 'topsecretusername'
  password: dG9wc2VjcmV0cGFzc3dvcmQK  # Base64 encoded 'topsecretpassword'

