
# kubectl expose deployment app --type=LoadBalancer --name=app --port=3000
kind: Deployment
metadata:
  name: app-secured
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-secured
  template:
    metadata:
      labels:
        app: app-secured
    spec:
      containers:
      - name: app-secured
        image: app-secured
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
