
# kubectl expose deployment app --type=LoadBalancer --name=app --port=3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-secured
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-secured
  template:
    metadata:
      labels:
        app: app-secured
    spec:
      containers:
      - name: app-secured
        image: app-secured
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: TYPE
          value: "app-secured"
        securityContext:
          #runAsUser: 1000
          allowPrivilegeEscalation: false 
          privileged: false
          #runAsNonRoot: true
        volumeMounts:
        - name: app-secret-volume
          mountPath: "/etc/app-secret"  # The path in the container where the secret will be mounted
      volumes:
      - name: app-secret-volume
        secret:
          secretName: app-secret  # The name of the secret to mount
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app-secured
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  username: dG9wc2VjcmV0dXNlcm5hbWU=  # Base64 encoded 'topsecretusername'
  password: dG9wc2VjcmV0cGFzc3dvcmQK  # Base64 encoded 'topsecretpassword'
