
# kubectl expose deployment app --type=LoadBalancer --name=app --port=3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: app
        imagePullPolicy: Never
        env:
        - name: TYPE
          value: "app"
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
---
# add a simple kubernetes secret 
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  username
  password
```

