# Use an official Node.js runtime as the base image
FROM node:14

# Set the working directory in the container to /app
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install the application dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Define the command to run the application
CMD [ "node", "index.js" ]

# Build the docker image
# docker build -t app .                                                                                                                                                 
# docker run -d -it -p 3000:3000 --rm app
# docker scout quickview app
# docker scout cves app