FROM ubuntu:22.04

# Patch image and install vim for convenience
RUN apt-get update \
      && apt-get -y dist-upgrade \
      && apt-get -y install \
      vim-tiny \
      && apt-get autoremove -y --purge \
      && apt-get -y clean \
      && apt-get -y autoclean \
      && rm -rf /var/lib/apt/lists/* \
      && find /var/cache/debconf -type f -print0 | xargs -0 rm -f \
      && find /var/cache/apt -type f -print0 | xargs -0 rm -f

# Add non root user
RUN useradd --uid 1000 npm

# docker build -t baseimage --file dockerfile-base .