# Use an official Node.js runtime as the base image
FROM node:14 as builder

# Set the working directory in the container to /app
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install the application dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Start a new, final stage to keep our image small and secure
FROM baseimage

# Configure container to start by default with the node user (UID 1000)
USER node

# Set the working directory
WORKDIR /app

# Copy files and grant the node user ownership on them
COPY --chown=node:node --from=builder /app .

# Define the command to run the application
CMD [ "node", "index.js" ]

# Build the docker image
# docker build -t app-secured --file dockerfile-secured .
# docker run -d -it -p 3000:3000 --rm app-secured
# docker scout quickview app-secured