# we will use this file to show 

# Use an official Node.js runtime as the base image
FROM node:14

# Set the working directory in the container to /app
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install the application dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Define the command to run the application
CMD [ "node", "index.js" ]

# 1. Minimize docker image size using multi-stage builds by using slim tagged node image

# 2. Secure image by using a non-root user.
